export const GET_NOTES_VALUE = 'GET_NOTES_VALUE';
export const INIT_SAVE_NOTES_VALUE = 'INIT_GET_NOTES_VALUE';
export const SAVE_NOTES_VALUE_SUCCESSFUL = 'SAVE_NOTES_VALUE_SUCCESSFUL';
export const SAVE_NOTES_VALUE_FAILED = 'SAVE_NOTES_VALUE_FAILED';

